<?php

namespace App\Console\Commands;

use App\Jobs\IndexRuleEmbedding;
use App\Models\Rule;
use Illuminate\Console\Command;

class IndexRules extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:index-rules';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Queue embedding generation for all rules (backfill).';

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        $count = Rule::count();

        if ($count === 0) {
            $this->info('No rules to index.');

            return;
        }

        $this->info("Dispatching embedding jobs for {$count} rule(s)...");

        Rule::chunkById(100, function ($rules) {
            foreach ($rules as $rule) {
                IndexRuleEmbedding::dispatch($rule);
            }
        });

        $this->info('Done. Embeddings will be generated by the queue worker.');
    }
}
