/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "logout": [],
    "dashboard": [],
    "request.create": [],
    "requests.index": [],
    "requests.approved": [],
    "requests.denied": [],
    "requests.detail": [
        {
            "name": "request_id",
            "required": true
        }
    ],
    "requests.store": [],
    "requests.pending": [],
    "requests.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "requests.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "rules": [],
    "rules.add": [],
    "rules.update": [],
    "rules.remove": [],
    "facilities": [],
    "facility.detail": [
        {
            "name": "facility_id",
            "required": true
        }
    ],
    "facility.schedule": [
        {
            "name": "facility",
            "required": true,
            "binding": "id"
        },
        {
            "name": "date",
            "required": true
        }
    ],
    "login.show": [],
    "login": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
